config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet'
  end
  
  devise_for :users
  
  get 'home/index'
  
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :liking_users, :through => :likes, :source => :user

  validates :content, presence: true

  paginates_per 50

  def like_icon(user)
    if self.is_liked?(user)
      'heart'
    else
      'heart-broken'
    end
  end

  def retweet_color
    self.count_rt > 0 ? 'primary' : 'muted'
  end

  def is_liked?(user)
    self.liking_users.include?(user)
  end

  def like(user)
    Like.create(user: user, tweet: self)
  end

  def remove_like(user)
    Like.where(user: user, tweet: self).destroy_all
  end

  def count_rt
    Tweet.where(rt_ref: self.id).count
  end

  def is_retweet?
    self.rt_ref.present? 
  end

  def tweet_ref
    Tweet.find(self.rt_ref)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes
  has_many :liked_tweets, :through => :likes, :source => :tweet

  def to_s
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @tweets = Tweet.all
    @tweets = Tweet.order(created_at: :desc).page params[:page]
    @tweet = Tweet.new
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :set_current_tweet, only: [:likes, :retweet]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  def likes
    if @tweet.is_liked?(current_user)
      @tweet.remove_like(current_user)
    else   
      @tweet.like(current_user)
    end  
    redirect_to root_path
  end

  def retweet
    Tweet.create(content: @tweet.content, user_id: current_user.id, rt_ref: @tweet.id)
    redirect_to root_path
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        # format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        # format.html { render :new, status: :unprocessable_entity }
        format.html { redirect_to root_path, alert: "Content is required" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def set_current_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/index.html.erb
<div class="list-group">
<br><br>
<% if user_signed_in? %>
    <div class="row">
        <%= render 'tweets/form', tweet: @tweet %>
    </div>
<% end %>

    <% @tweets.each do |tweet| %>
        <%= render 'tweets/single_tweet', tweet: tweet %>
    <% end %>
    <hr>
    
    <%= paginate @tweets %>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/navbar' %>

      <% if alert || notice %>
        <div class="alert alert-<%= alert ? 'danger' : 'success' %> text-center" role="alert">
          <%= alert %>
          <%= notice %>
        </div>
      <% end %>

      <div class="">
        <%= yield %>
      </div>
    </div>

    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="text-white ml-3" href="#">TWEET APP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end " id="navbarNav">
    <ul class="navbar-nav text-light">
      <li class="nav-item active nav-link">
        <%= link_to 'Home', root_path %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item nav-link text-right text-primary float-right">
          [Hola <%= "#{current_user.username}" %>]
        </li>
        <li class="nav-item nav-link text-right float-right text-light">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class="nav-item nav-link text-light">
          <%= link_to 'Sign up', new_user_registration_path %>
        </li>
        <li class="nav-item nav-link text-light">
          <%= link_to 'Log in', new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/tweets/_form.html.erb
<div class="col-6 border-white p-2 mt-2 mx-auto">
  <%= form_with(model: tweet, local: true) do |form| %>
    <% if tweet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
          <% tweet.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <!-- <%= form.label :content %>--> 
      <%= current_user.username %> dice: <br> <br>
      <%= form.text_area :content, class: "w-100 p-2" %>
    </div>

    <!-- <div class="field">
      <%= form.label :user_id %>
      <%= form.text_field :user_id %>
    </div>-->

    <div class="actions float-right">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/tweets/_single_tweet.html.erb
<div class="col-6 border-white p-3 mt-2 mx-auto">
    <div clas="list-unstyled">
        <%= link_to "<i class='fas fa-calendar'></i> ".html_safe+time_ago_in_words(tweet.created_at), tweet %> <%=  %>
    </div>
    <br>
    <%= image_tag (tweet.user.avatar), :class => "align-self-center mr-3 avatar-in-tweet rounded-circle", size: "50x50" %>
    <%= tweet.content %> 
    <br><br>
    <div class="container-fluid">
        <div class="d-inline">
            <%= link_to "<i class='fas fa-#{tweet.like_icon(current_user)} text-danger'></i>".html_safe, tweet_likes_path(tweet), method: :post %>
            <%= tweet.likes.count %>
        </div>
        <div class="float-right">
            <%= tweet.count_rt %>
            <%= link_to "<i class='fas fa-retweet text-#{tweet.retweet_color}'></i>".html_safe, tweet_retweet_path(tweet), method: :post %>
            <% if tweet.is_retweet? %>
                <%= link_to "Retweet...", tweet.tweet_ref %>
            <% end %>
        </div>
    </div>
</div>

app/views/tweets/edit.html.erb
<h1 class="text-center">Edit your Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<br> <br>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.content %></td>
        <td><%= tweet.user.to_s %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<br><br>
<h1 class="text-center">New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<br><br>
<div class="col-3 border-white p-0 mt-1 m-auto">
  <p>
    <strong>Content:</strong>
    <%= @tweet.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @tweet.user.to_s %>
  </p>

  <h4>Likes</h4>
  <% @tweet.liking_users.each do |user| %>
    <%= image_tag(user.avatar, class: "avatar-in-tweet rounded-circle", size: "50x50") %>
  <% end %>
  <br>
  <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
  <%= link_to 'Back', root_path %>
</div>